
% Presentación de la interfaz
function Senales
clear,clc,cla,close all
figdiag=figure('Units','Pixels',...
               'Position',[1000 500 1000 500],...
               'Name','SEÑALES BASICAS', ...
               'Menubar','none', ...
               'color',[0 0 0]);
axes('Units','Normalized',...
     'Position',[0 0 1 1]);
scrsz = get(0, 'ScreenSize');
pos_act=get(gcf,'Position');
xr=scrsz(3) - pos_act(3);
xp=round(xr/2);
yr=scrsz(4) - pos_act(4);
yp=round(yr/2);
set(gcf,'Position',[xp yp pos_act(3) pos_act(4)]);
[x,map]=imread('fondo.jpg','jpg');
image(x),colormap(map),axis off,hold on

text(50,130,'SEÑALES BASICAS','Fontname', ...
'Cooper Black','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',30,'color',[1 1 1]);

text(50,180,'OPERACIONES CON SEÑALES','Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',14,'color',[1 1 1]);

text(50,420,'PRESENTADO POR:','Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',25,'color',[1 1 1]);

text(50,540,[...
    'NELSON HERNAN MUÑOZ BURBANO '
    'BRIAN ALEXIS QUINTERO BEDOYA'
    'LEIDY TATIANA ROJAS FORERO  '
    'MIGUEL ALEJANDRO SUAREZ USSA'],'Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',14,'color',[1 1 1]);

botonContinuar=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.87 .03 .12 .05], ...
'String','CONTINUAR',...
'Callback','clear all;close all;clc; TiposDeSenales;');

