function TiposDeSenales
clear,clc,cla,close all
figdiag=figure('Units','Pixels',...
               'Position',[1000 500 1000 500],...
               'Name','TIPOS DE SEÑALES', ...
               'Menubar','none', ...
               'color',[0 0 0]);
axes('Units','Normalized',...
     'Position',[0 0 1 1]);
scrsz = get(0, 'ScreenSize');
pos_act=get(gcf,'Position');
xr=scrsz(3) - pos_act(3);
xp=round(xr/2);
yr=scrsz(4) - pos_act(4);
yp=round(yr/2);
set(gcf,'Position',[xp yp pos_act(3) pos_act(4)]);
[x,map]=imread('fondo.jpg','jpg');
image(x),colormap(map),axis off,hold on

text(300,130,'TIPOS DE SEÑALES','Fontname', ...
'Cooper Black','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',30,'color',[1 1 1]);

botonSContinuas=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.4 .5 .20 .1], ...
'String','SEÑALES CONTINUAS',...
'Callback','clear all; close all;clc;operacionesSenales;');

botonSDiscretas=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.4 .3 .20 .1], ...
'String','SEÑALES DISCRETAS',...
'Callback','clear all; close all;clc; SENALES_DISCRETAS;');

botonAtras=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.815 .015 .08 .05], ...
'String','ATRAS',...
'Callback','clear all; close;clc; Senales;');

botonSalir=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.9 .015 .08 .05], ...
'String','SALIR',...
'Callback','clear all; close all;clc;');


 

