% Presentación de la interfaz
function Senales
clear,clc,cla,close all
figdiag=figure('Units','pixels',...
              'Position',[1000 550 1000 550],...
              'NumberTitle','off',...
              'Name','ECUALIZADOR DIGITAL DE 6 CANALES', ...
              'MenuBar','none', ...
              'Color',[0 0 0]);
axes('Units','Normalized',...
     'Position',[0 0 1 1]);
scrsz = get(0, 'ScreenSize');
pos_act=get(gcf,'Position');
xr=scrsz(3) - pos_act(3);
xp=round(xr/2);
yr=scrsz(4) - pos_act(4);
yp=round(yr/2);
set(gcf,'Position',[xp yp pos_act(3) pos_act(4)]);
[x,map]=imread('eq.jpg','jpg');
image(x),colormap(map),axis off,hold on

text(90,30,'SEÑALES Y SISTEMAS','Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',30,'color',[1 1 1]);

text(50,120,'ECUALIZADOR DIGITAL DE 6 CANALES','Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',24,'color',[1 1 1]);

text(30,170,'PRESENTADO POR:','Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',22,'color',[1 1 1]);

text(30,200,[...
    'NELSON HERNAN MUÑOZ BURBANO '
    'BRIAN ALEXIS QUINTERO BEDOYA'
    'LEIDY TATIANA ROJAS FORERO  '
    'MIGUEL ALEJANDRO SUAREZ USSA'],'Fontname', ...
'Times New Roman','Fontangle','Italic','Fontweight','Bold', ...
'Fontsize',14,'color',[1 1 1]);

botonContinuar=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.77 .015 .12 .05], ...
'String','CONTINUAR',...
'Callback','clear all;close all;clc; Ecualizador6CH;');

botonSalir=uicontrol('Style','pushbutton', ...
'Units','normalized', ...
'Position',[.9 .015 .08 .05], ...
'String','SALIR',...
'Callback','clear all; close all;clc;');